node('master') {

stage('Git CheckOut') {
  git branch: 'main', url: 'https://github.com/amitvashisttech/devcloud-dxc-30Mar2021.git'
 }

def Project_Path="02-App-Code/petclinic-code"

dir(Project_Path) {

stage('Maven Clean') {
  sh 'mvn clean'
 }

stage('Maven Compile') {
  sh 'mvn compile'
 }

stage('Maven Testing') {
  sh 'mvn test'
 }

stage('Maven Package') {
  sh 'mvn package'
 }

stage('Archive Artifacts') { 
archiveArtifacts artifacts: 'target/*.war', followSymlinks: false 
 }

stage('Publish Test Results') {   
junit 'target/surefire-reports/TEST-*.xml'  
 }
}
}
